/**
 * Budget Planner API
 * Application to track expenses and finance
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mohit@penguincoders.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface LoginRequestDto {
  username: string;
  password: string;
}
