/**
 * Budget Planner API
 * Application to track expenses and finance
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mohit@penguincoders.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Expense } from './expense';


export interface MonthlyExpenseResponse { 
    expenses?: Array<Expense>;
    total?: number;
    categoryTotal?: { [key: string]: number; };
}

